name: pytest
on: [workflow_dispatch]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [windows-latest]
        python-version: [3.10]
    steps:
    - uses: actions/checkout@master

    - name: Setup Python  
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run unit tests
      run: |
        pip install -r tests/test_requirements.txt
        pip install -e .
        pytest tests/
